spring.application.name=BuyNow
spring.datasource.url=jdbc:mysql://localhost:3306/BuyNowDB
spring.datasource.username=root
spring.datasource.password=Sasack
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

file.upload-dir=./upload